In [14]:
# changing shape in an array :

arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Array broadcasting :
a =np.array([[0.0,0.0,0.0],[10.0,10.1,10.2]])
b =np.array([[1.0,2.0,3.0]])
print("first array and second array",a+b) 


first array and second array [[ 1.   2.   3. ]
 [11.  12.1 13.2]]


In [22]:
# Vectorization :
print(np.sum(np.arange(15000)))
%timeit np.sum(np.arange(15000))

112492500
13.6 µs ± 88.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
import math
# vectorized operation

print("time taken by vectorized :",end='')
%timeit np.exp(np.arange(150))

time taken by vectorized :1.73 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
# one d Array:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [25]:
# Two d array :
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [30]:
# split into array
arr = np.array([1,2,3,4,5,6])
newarr =np.array_split(arr,3)
print(newarr[1])
print(newarr[0])
print(newarr[2])

[3 4]
[1 2]
[5 6]


In [33]:
# spliting 2 D Array :

arr =np.array([[1,2],[3,4],[5,6]])
newarr =np.array_split(arr,5)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]


In [37]:
# copy :

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[4]=42
print(arr)
print(x)

[ 1  2  3  4 42]
[1 2 3 4 5]


In [42]:
# view :
arr = np.array([1,2,3,4,5,6])
x = arr.view()
arr[0] =66
print(arr)
print(x)

# both are changed


[66  2  3  4  5  6]
[66  2  3  4  5  6]


In [77]:

#stack( )  function:

arr_1 =np.array([[1,2,3],[-1,-2,-3]])
print("1st input array :\n ",arr_1)

arr_2 = np.array([[4,5,6],[-4,-5,-6]])
print("2nd input array :\n",arr_2)

out_arr = np.stack((arr_1,arr_2),axis =0)
print("Out put stacked array :\n",out_arr)


out_arr_1 =np.stack((arr_1,arr_2),axis=1)
print("plus_one : \n",out_arr_2)

out_arr_2 =np.stack((arr_1,arr_2),axis=-1)
print("minus : \n",out_arr_2)

1st input array :
  [[ 1  2  3]
 [-1 -2 -3]]
2nd input array :
 [[ 4  5  6]
 [-4 -5 -6]]
Out put stacked array :
 [[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
plus_one : 
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[-1 -4]
  [-2 -5]
  [-3 -6]]]
minus : 
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[-1 -4]
  [-2 -5]
  [-3 -6]]]
