In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
arr= np.array([1,2,3,4])
print(arr[0])
print(arr[3])

1
4


In [10]:
arr =np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])
print(arr[0:6])

[2 3 4 5]
[1 2 3 4 5 6]


In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [16]:
arr= np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,8)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [18]:

new_1 = np.array_split(arr,9)
print(new_1)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [19]:
arr = np.array([1,2,3,4,5,6])
x =np.where(arr==4)
print(x)

(array([3], dtype=int64),)


In [20]:
# asscending order:

arr =np.array([3,2,4,5])
print(np.sort(arr))

[2 3 4 5]


In [21]:
# decending order
arr =np.array([3,2,4,5])
x =np.sort(arr)
y=x[::-1]
print(y)


[5 4 3 2]
